spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          
      routes:
      - id: one
        uri: lb://welcome-api
        predicates:
        - Path = /welcome
      - id: two
        uri: http://localhost:9091
        predicates:
        - Path=/greet/**
    

  application:
    name: API-GATEWAY
  
  
          
server:
  port: 3333
  
  
 
  
  
  

