spring:
  application:
    name: welcome-api
  boot:
    admin:
      client:
        url: http://localhost:1111/
        
management:
  endpoints:
    web:
      exposure:
        include: '*'
  
       
server:
  port: 8081
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  
  
